apiVersion: redis.redis.opstreelabs.in/v1beta2
kind: RedisCluster
metadata:
  name: redis-cluster
  namespace: default
spec:
  clusterSize: 3
  clusterVersion: v7
  env:
    - name: ALLOW_EMPTY_PASSWORD
      value: "yes"
    - name: VALKEY_NODES
      value: "nil"
  podSecurityContext:
    runAsUser: 1000
    fsGroup: 1000
  redisLeader:
    livenessProbe:
      initialDelaySeconds: 60
      periodSeconds: 20
      failureThreshold: 10
  redisFollower:
    livenessProbe:
      initialDelaySeconds: 60
      periodSeconds: 20
      failureThreshold: 10
  persistenceEnabled: true
  kubernetesConfig:
    image: quay.io/opstree/redis:v7.2.7
    imagePullPolicy: IfNotPresent
  storage:
    volumeClaimTemplate:
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 10Gi
